{
    "name": """Assistant ChatGPT Integration""",
    "summary": """Assistant ChatGPT integration powered by UnitSoft""",
    "category": "Discuss",
    "images": ["static/description/banner.png"],
    "version": "17.0.2.1.0",
    "author": "UnitSoft",
    "support": "",
    "website": "https://unitsoft.com.ua/",
    "license": "OPL-1",
    "price": 50,
    "currency": "EUR",
    "depends": ["base_automation", "base", "crm", "im_livechat"],
    "external_dependencies": {"python": ["openai"] ,"bin": []},
    "data": [
        "security/us_assistant_groups.xml",
        "security/ir.model.access.csv",
        "wizard/vector_store_wizard_view.xml",
        "views/gpt_assistant_views.xml",
        "views/im_livechat_channel_views.xml",
        "views/chatbot_script_step_views.xml",
        "views/vector_store_views.xml",
        "views/res_config_settings_views.xml",
        "data/im_livechat_chatbot_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "us_assistant/static/src/core/**/*",
            "us_assistant/static/src/discuss/core/**/*",
        ],
        'im_livechat.assets_embed_core': [
            "us_assistant/static/src/core/common/thread_service.js",
        ],
    },
    "demo": [
        "data/gpt_assistant_demo.xml",
    ],
    "qweb": [],
    "post_load": None,
    "application": False,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}